### ISSUE TITLE
Localization for website (FR and ZH) 

### ISSUE THREAD

**Issue by dhowe** [dhowe/TrackMeNot-website#1]
http://localhost/git/TrackMeNot/index.html?zh
http://localhost/git/TrackMeNot/index.html?fr

French is ready to be done: see https://cs.nyu.edu/trackmenot/fr/

Chinese translations are waiting on @vtoubiana to unlock his directories on the server

**Comment by cqx931** [comment]
FR: https://github.com/dhowe/TrackMeNot/commit/4b97ed32e7ab4867e33d112028e27c1e0d56360a
Is it only partially translated?

**Comment by dhowe** [comment]
Can you add a bit of padding at the arrow below:

![image](https://user-images.githubusercontent.com/737638/26862492-422cc672-4b7e-11e7-807b-ce37aaa0ce11.png)

**Comment by dhowe** [comment]
> Is it only partially translated?

apparently

**Comment by cqx931** [comment]
Minor tweak here: https://github.com/dhowe/TrackMeNot/commit/ef5299b80fa66e93d0d216c488114298db426b44

**Comment by dhowe** [comment]
Ready to add Chinese

**Comment by dhowe** [comment]
@cqx931 status?

**Comment by cqx931** [comment]
Here are the changes: https://github.com/dhowe/TrackMeNot/tree/gh-pages, already pushed to dhowe/Trackmenot, gh-pages

**Comment by cqx931** [comment]
close
