### ISSUE TITLE
JS locale code over-riding user selection

### ISSUE THREAD

**Issue by dhowe** [dhowe/TrackMeNot-website#4]
Reported by @vtoubiana

To recreate:
1. access tmn from france or china (page should switch to that language)
2. click 'en' link at top of page
3. language does not change

we may need another query-string parameter, something like `&force=true`, for when the user manually selects a language

**Comment by cqx931** [comment]
fixed https://github.com/dhowe/TrackMeNot/commit/df1f26df0e9681fe266d5be849ad44fb1d1781b4

**Comment by dhowe** [comment]
@vtoubiana please check and close if ok
